- src/main/java/ch/heigvd/res/chill/domain/jehrensb/MaiselsWeissbier.java
- src/test/java/ch/heigvd/res/chill/domain/jehrensb/MaiselsWeissbierTest.java
> Add Maisels Weissbier with tests.

- src/main/java/ch/heigvd/res/chill/domain/jehrensb/MaiselsWeissbier.java
- src/main/java/ch/heigvd/res/chill/domain/jehrensb/SchneiderWeisse.java
- src/test/java/ch/heigvd/res/chill/domain/jehrensb/MaiselsWeissbierTest.java
- src/test/java/ch/heigvd/res/chill/domain/jehrensb/SchneiderWeisseTest.java
> Add new beer: Schneider Weisse

- src/main/java/ch/heigvd/res/chill/domain/jehrensb/Guinness.java
- src/test/java/ch/heigvd/res/chill/domain/jehrensb/GuinnessTest.java
> Add Guinness as new beer

- src/main/java/ch/heigvd/res/chill/domain/jehrensb/Kilkenny.java
- src/test/java/ch/heigvd/res/chill/domain/jehrensb/KilkennyTest.java
> Add new beer: Kilkenny

- src/main/java/ch/heigvd/res/chill/domain/alexisallemann/Feldschlosschen.java
- src/test/java/ch/heigvd/res/chill/domain/alexisallemann/FeldschlosschenTest.java
> Added Feldschlosschen with tests

- src/main/java/ch/heigvd/res/chill/domain/jbstand/Valaisanne.java
- src/test/java/ch/heigvd/res/chill/domain/jbstand/ValaisanneTest.java
> Add Valaisanne Beer and tests

- src/main/java/ch/heigvd/res/chill/domain/delphscherler/Mojito.java
- src/test/java/ch/heigvd/res/chill/domain/delphscherler/MojitoTest.java
> Add Mojito with tests

- src/main/java/ch/heigvd/res/chill/domain/hakimbalestrieri/HotChocolate.java
- src/test/java/ch/heigvd/res/chill/domain/hakimbalestrieri/HotChocolateTest.java
> add hot chocolate with tests

- src/main/java/ch/heigvd/res/chill/domain/hakimbalestrieri/Milk.java
- src/test/java/ch/heigvd/res/chill/domain/hakimbalestrieri/MilkTest.java
> add milk with tests

- src/main/java/ch/heigvd/res/chill/domain/alexisallemann/Heineken.java
- src/test/java/ch/heigvd/res/chill/domain/alexisallemann/HeinekenTest.java
> Heineken class created and tested

- src/main/java/ch/heigvd/res/chill/domain/ggeggc/Leffe.java
- src/test/java/ch/heigvd/res/chill/domain/ggeggc/LeffeTest.java
Ajout d'une bière de marque Leffe
> Ajout bière LEFFE

- src/main/java/ch/heigvd/res/chill/domain/kyoden28/Sagres.java
- src/test/java/ch/heigvd/res/chill/domain/kyoden28/SagresTest.java
> Add Sagres with test

- src/main/java/ch/heigvd/res/chill/domain/kyoden28/SuperBock.java
- src/test/java/ch/heigvd/res/chill/domain/kyoden28/SuperBockTest.java
> Add SuperBock with tests

- src/main/java/ch/heigvd/res/chill/domain/aloischristen/Perrier.java
- src/test/java/ch/heigvd/res/chill/domain/aloischristen/PerrierTest.java
Now we have something for the "fillettes" ;)
close #41
> Added Perrier with test coverage

- src/main/java/ch/heigvd/res/chill/domain/mascot27/BiereFranchesMontagnes.java
- src/test/java/ch/heigvd/res/chill/domain/mascot27/BiereFranchesMontagnesTest.java
> + bfm implementation and test coverage

- src/main/java/ch/heigvd/res/chill/domain/mascot27/Corona.java
- src/test/java/ch/heigvd/res/chill/domain/mascot27/CoronaTest.java
> + Corona implementation and test coverage

- src/main/java/ch/heigvd/res/chill/domain/alexmottier/Barbar.java
- src/test/java/ch/heigvd/res/chill/domain/alexmottier/BarbarTest.java
> Add Barbar + tests

- src/main/java/ch/heigvd/res/chill/domain/alexmottier/SWAF.java
- src/test/java/ch/heigvd/res/chill/domain/alexmottier/SWAFTest.java
> Add SWAF + tests

- src/main/java/ch/heigvd/res/chill/domain/jbstand/Delirium.java
- src/test/java/ch/heigvd/res/chill/domain/jbstand/DeliriumTest.java
> Add Delirium and tests

- src/main/java/ch/heigvd/res/chill/domain/ggeggc/SeizeSoixanteQuatre.java
- src/test/java/ch/heigvd/res/chill/domain/ggeggc/SeizeSoixanteQuatreTest.java
J'ajoute une deuxième bière de marque 1664, écrite SeizeSoixanteQuatre en java pour ne pas avoir de problème avec le nommage de variable.
> Ajout bière marque 1664
